client_client:
    resource: "@QwerLottoClientBundle/Resources/config/routing/client.xml"
    prefix:   /clien

QwerLottoClientBundle_currency:
    resource: "@QwerLottoClientBundle/Resources/config/routing/currency.xml"
    prefix:   /currency
    
QwerLottoClientBundle_currency_lala:
    resource: "@QwerLottoClientBundle/Controller/"
    type:     annotation
    prefix:   /
