client_client:
    resource: "@ClientBundle/Resources/config/routing/client.xml"
    prefix:   /clien

ClientBundle_currency:
    resource: "@ClientBundle/Resources/config/routing/currency.xml"
    prefix:   /currency
    
ClientBundle_currency_lala:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

